---
- name: when and conditional playbook example
  hosts: all
  become: yes
  tasks:
    - name: install git and nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx        
      when: inventory_hostname in groups["mygroup"]
...

