---
- name: commands module playbook examples
  hosts: all
  tasks:
    - name: list the files
      command: ls -lrth /home/vagrant/

    - name: run the script on target node
      script: example-1-script.sh

    - name: copy example-1-script.sh to remote machine for next task
      copy:
        src: ./example-1-script.sh
        dest: /home/vagrant/

    - name: execute shell command
      shell: sh /home/vagrant/example-1-script.sh
...